### ISSUE TITLE
publish the addon as a service?

### ISSUE THREAD

**Issue by frostworx** [hassio-addons/addon-emqx#106]
First of all thank you for the great addon.
I already use it for many months without any problems.

Today I recognized that it doesn't work with the [birdnet-pi addon](https://github.com/alexbelgium/hassio-addons/tree/master/birdnet-pi) which recently got mqtt broker autodetection.

I opened an issue [here](https://github.com/alexbelgium/hassio-addons/issues/1477) and the author [suggested](https://github.com/alexbelgium/hassio-addons/issues/1477#issuecomment-2227268793) that you should publish your addon as a service:

quote:

```
the owner should do that in the config.json of the addon

EDIT : through the "discovery" tag as seen in https://developers.home-assistant.io/docs/add-ons/configuration/
```

He's working on a manual override, so it would not be required on birdnet-pi side, but it might be interesting for you to add that feature anyway.

**Comment by frenck** [comment]
I can't, as this add-on doesn't provide a service out of the box. Additionally, the add-on provides a level of flexibility that I'm never able to provide all needed fields for the service (as they can be changed or don't have to be activated).

Nevertheless, thanks for the suggestion. 👍 

../Frenck

**Comment by frostworx** [comment]
thanks for the reply!
