### ISSUE TITLE
Zigbee2MQTT Connection Setup Issue

### ISSUE THREAD

**Issue by nicocoetzee** [hassio-addons/addon-emqx#21]
Hello - 

I would love some help as I have a few hours trying to figure this out. I've also read most I could find online with my luck.

I successfully installed EMQX, created the user, and authenticated it.

In MQTT, I have successfully "Re-configured MQTT" with the correct broker info, etc. When I listen to a topic, I can see it in the EMQX dashboard in Topics.

My trouble lies with Zigbee2MQTT. I cannot get it to talk to the EMQX database. This is the error I'm getting:

[11:54:55] INFO: Preparing to start...
[11:54:55] INFO: Socat not enabled
[11:54:56] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-01-06 11:54:56: Logging to console and directory: '/config/zigbee2mqtt/log/2023-01-06.11-54-56' filename: log.txt
Zigbee2MQTT:info  2023-01-06 11:54:56: Starting Zigbee2MQTT version 1.29.1 (commit #unknown)
Zigbee2MQTT:info  2023-01-06 11:54:56: Starting zigbee-herdsman (0.14.83)
Zigbee2MQTT:info  2023-01-06 11:54:57: zigbee-herdsman started (resumed)
Zigbee2MQTT:info  2023-01-06 11:54:57: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20210708,"transportrev":2},"type":"zStack3x0"}'
Zigbee2MQTT:info  2023-01-06 11:54:57: Currently 0 devices are joined:
Zigbee2MQTT:warn  2023-01-06 11:54:57: `permit_join` set to  `true` in configuration.yaml.
Zigbee2MQTT:warn  2023-01-06 11:54:57: Allowing new devices to join.
Zigbee2MQTT:warn  2023-01-06 11:54:57: Set `permit_join` to `false` once you joined all devices.
Zigbee2MQTT:info  2023-01-06 11:54:57: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2023-01-06 11:54:57: Connecting to MQTT server at mqtt//a0d7b954-emqx:1883
Zigbee2MQTT:error 2023-01-06 11:54:57: MQTT failed to connect, exiting...
Zigbee2MQTT:info  2023-01-06 11:54:57: Stopping zigbee-herdsman...

What should the username and password be in Zigbee2MQTT? I've tried the original credentials that worked with Mosquito and also that I authenticated in EMQX, but nothing seems to work.

I'm sure I'm over looking something stupid, but I would really appreciate any help you can provide.

Many thanks,
n.

**Comment by nicocoetzee** [comment]
Hi Frenck -

Thank you for the response. For some reason, when I added the EMQX
credentials directly into the Z2M configuration file vs. the UI, it works!
Not sure why, but it's up and running now.

Many thanks,
n.

**Comment by frenck** [comment]
Alright, happy to hear it is running  👍
