### ISSUE TITLE
Container Health Check fails

### ISSUE THREAD

**Issue by ipm79** [hassio-addons/addon-emqx#36]
# Problem/Motivation

Container Health Check fails - HASS supervisor tries to restart container even though it is working properly.
Container health is marked as "unhealthy" when checked with docker -ps
```
CONTAINER ID   IMAGE                                                          COMMAND           CREATED          STATUS                      PORTS                                       NAMES
64f06a0896dd   ghcr.io/hassio-addons/emqx/amd64:0.2.5                         "/init"           11 minutes ago   Up 11 minutes (unhealthy)                                               addon_a0d7b954_emqx
```

## Expected behavior

Container health check to work properly.

## Actual behavior

Every time HASS is restarted the HASS supervisor restarts the EMQX container multiple times because it is marked as unhealthy. This happens about 10 times - then the HASS supervisor gives up because of it's restart rate limit of 10 times in 30mins.
```
23-03-27 21:11:22 WARNING (MainThread) [supervisor.addons.addon] Watchdog found addon EMQX is unhealthy, restarting...
23-03-27 21:11:22 INFO (SyncWorker_6) [supervisor.docker.interface] Stopping addon_a0d7b954_emqx application
23-03-27 21:11:27 INFO (SyncWorker_6) [supervisor.docker.interface] Cleaning addon_a0d7b954_emqx application
23-03-27 21:11:27 INFO (SyncWorker_10) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/emqx/amd64 with version 0.2.5

...

<Task finished name='Task-3096043' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:989> exception=AddonsJobError('Rate limit exceeded, more then 10 calls in 0:30:00')>
```

## Steps to reproduce

If the health check command from the Dockerfile is tried manually inside the container the error message is:
```
root@a0d7b954-emqx:/# /opt/emqx/bin/emqx_ctl
Node 'emqx@ha.local' not responding to pings.
```

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by mundschenk-at** [comment]
The health check fails because the Erlang network stack thinks it can't resolve `ha.local` (or `homeassistant.local` as its set up by default). I've experimented and it could ping itself if I set up the node as `emqx@127.0.0.1` (and then the health check is clean). Researching the issue, I've found a [blog post that describes setting up an alias](https://techoverflow.net/2022/09/27/how-to-fix-docker-emqx_ctl-node-emqxnode1-emqx-mydomain-com-not-responding-to-pings/) in the Docker config.

**Comment by mundschenk-at** [comment]
I am really not sure why Erlang is having trouble, when I manually installed some network tools on the image, `homeassistant.local` could be resolved fine from the shell. There are some [low-level configs for the Erlang network runtime](https://www.erlang.org/doc/apps/erts/inet_cfg.html) regarding name resolution, but I'm not sure where those could be set for EMQX.

**Comment by mundschenk-at** [comment]
Still an issue. You can add the following to the configuration as a workaround:
```yaml
- name: EMQX_NODE__NAME
  value: emqx@127.0.0.1
```

This creates a new node however, so any in-system configuration needs to be done again.

**Comment by mundschenk-at** [comment]
Still an issue.

**Comment by mundschenk-at** [comment]
Still an issue.
