### ISSUE TITLE
High CPU load with only little traffic

### ISSUE THREAD

**Issue by TheDK** [hassio-addons/addon-emqx#5]
# Problem/Motivation

With only one ESPresense node connected and ~2-4 messages / second the add-on shows very high CPU load on a HA Blue:

![grafik](https://user-images.githubusercontent.com/5020623/192144282-6c8b228e-c35a-4379-bb85-03aea21d466b.png)

![grafik](https://user-images.githubusercontent.com/5020623/192144153-fb588d74-9bf0-4473-a093-725a8b05477f.png)
(I think the dropped messages are ESPresense sending information that HA room-mqtt does not listen to)

Mosquitto in comparison was around 1-5% CPU load for exactly the same workload.

## Steps to reproduce

Just install and drop-in replacement, no individual config, just users created.

## Proposed changes

Just wanted to know if this is to expect or due to experimental state. I use the most recent version of the add-on...

**Comment by TheDK** [comment]
I was just wondering if 100-150% CPU load should be the case - for comparison: the HA container never goes above 40-50%, NodeRED, ZWaveJS2MQTT, etc. never in the double digits.

Do you see comparable load in your enviroment? If that is normal behaviour my quesstions is answered and yes, not a bug.

If I look at Glances this seems only to be the case when the Dashboard is open - once again, if this is to be expected this can be closed.

**Comment by zetkasprzyk** [comment]
I've noticed quite a bump in CPU usage after installing and running emqx.
With mosquito - HA VM sits at around 7%
With EMQX - at about 15%
So not sure if this is any bug. EMQX is much "heavier" than mosquito.

**Comment by frenck** [comment]
> Do you see comparable load in your environment?

Not in general use, around 1%-ish, with a spike when, e.g., the Dashboard is used or when things like Zigbee2MQTT start up (and dump loads of data).

> this seems only to be the case when the Dashboard is open

It can be expected that more resources are used when using the dashboard. It shows data (live and by polling).

**Comment by TheDK** [comment]
I monitored for a week, CPU was continuously loaded double as before, even though the UI was not open. Switched back to Mosqitto for now, but left it in place for debugging…
