### ISSUE TITLE
Any way to store the user id and password in config? 

### ISSUE THREAD

**Issue by shawndamon** [hassio-addons/addon-emqx#50]
# Problem/Motivation
I have set it up and everything works well. Just wondering if there is a way for me to store the Username and Password somewhere in the configuration file ? 

> (Why the issue was filed)
The behavior currently is that when I select EMQX, I need to keep entering the user id and password

**Comment by mundschenk-at** [comment]
You can set the token timeout to a year (or some other long timeframe):
```yaml
- name: EMQX_DASHBOARD__TOKEN_EXPIRED_TIME
  value: 365d
```
