### ISSUE TITLE
Logging and Monitoring page not loading

### ISSUE THREAD

**Issue by InputMoe** [hassio-addons/addon-emqx#51]
# Problem/Motivation

The logging page does not load and shows an empty page.
The same with the Monitoring menu, when "system" is selected. If you click on "integration" a page is loaded.

## Expected behavior

Logging page loads like described in:
https://www.emqx.io/docs/en/v5.0/observability/log.html#configure-logging-via-dashboard

same with the Monitoring page.

## Actual behavior

Both pages do not load and just show an empty page.

## Steps to reproduce

1. Install the EMQX add-on.
2. Log in.
3. Go in the menu on the left side to the Logging or Monitoring link and open it.

## Proposed changes

Well I don't know the reason, why these pags are not loading. The standard documentation assumes, that after the install the pages are available and can be used to configure the logging itself. So it seems to be something with the installation.

**Comment by sinclairpaul** [comment]
Looks for /api/v5/schemas/hotconf in the console, not sure we really want to do a rewrite here.
