### ISSUE TITLE
Local Database Storage and backup

### ISSUE THREAD

**Issue by mzac** [hassio-addons/addon-emqx#6]
# Problem/Motivation

I'm trying to figure out where the local database is stored on the system.  The only mount inside the container appears to be the /ssl directory.  I also don't see any docker volumes that were created.

I'd also like to make sure that the data is being kept as part of the Home Assistant backup.

## Expected behavior

Some other addons can store data in /config

## Actual behavior

Can't find where the storage is

## Proposed changes

Documentation should list where the local storage is kept or put it in /config

**Comment by frenck** [comment]
> I'd also like to make sure that the data is being kept as part of the Home Assistant backup.

Data is stored in the internal add-on storage, and thus part of the backups. This is how add-ons are supposed to work by design.

../Frenck
