### ISSUE TITLE
High Ram and CPU Spikes causing OOM

### ISSUE THREAD

**Issue by Weafyr** [hassio-addons/addon-emqx#60]
I run fresh installation of home assistant os on brand new odroid m1 (4GB version) and because of better HW I decided to go with better mqtt broker. But after installation of emqx addon, the ram and cpu consumption started spiking.

Detailed description (not from me) can be found here: https://github.com/emqx/emqx/issues/10509

I have exactly same symptoms as creator of the issue in emqx repository.

![image](https://github.com/hassio-addons/addon-emqx/assets/24644737/9879dde5-03b2-420d-bd47-65d61888117b)
![image](https://github.com/hassio-addons/addon-emqx/assets/24644737/96d9bef0-e5fc-471c-93a6-c2d1616be25a)

**Comment by Weafyr** [comment]
![image](https://github.com/hassio-addons/addon-emqx/assets/24644737/6df71ffe-99c1-42fa-9571-aec8b651af6f)
![image](https://github.com/hassio-addons/addon-emqx/assets/24644737/7303b8c5-9bac-4d88-836a-b474f81fffe9)
![image](https://github.com/hassio-addons/addon-emqx/assets/24644737/5ca75112-c169-4d04-ba56-6780ddc6f306)

**Comment by KBrownConsulting** [comment]
I'm experiencing the same issue on v0.2.10

**Comment by ahochsteger** [comment]
The same with v0.2.10 of EMQX HA Add-on, Home Assistant 2023.9.2, Supervisor 2023.09.2, Operating System 10.5, Frontend 20230911.0 on a Raspberry Pi 4B with 4GB (64bit Home Assistant OS).
The RAM usage of the EMQX add-on continuously flaps between 2.2% and 43.6%.

**Comment by crls00** [comment]
I'm also having the same issue with version 0.2.10 of the addon. Frequent memory spikes reaching over 94%, alarms every 3 minutes... 33 mqtt devices.

Home Assistant 2023.9.2
Supervisor 2023.09.2
Operating System 10.5
Frontend 20230911.0 - latest

EXSi VM running on i5 NUC

**Comment by mikimite** [comment]
Hi, 
I think I may found it:
[https://github.com/hassio-addons/addon-emqx/blob/718b5d880f84611cd79b5cdb79adde623776990e/emqx/Dockerfile#L31](url)

Health check is running every 5 seconds the comand 
`
/opt/emqx/bin/emqx_ctl status || exit 1
`

this starts a new erlang VM machine and causes spikes.
if you log into the container with 
`docker exec -it {your_container_name} /bin/sh` and start running `ps -axf` repeated times at some point you will capture a new process and some of his sons

if you execute that same command: 
`/bin/sh -c /opt/emqx/bin/emqx_ctl status || exit 1` you will start the same process and observe that the cpu usage and memory goes up and new erlang machine starts

**Comment by mikimite** [comment]
Confirmed by deploying a local modified addon. I stay like this until new release

**Comment by RemCom** [comment]
I had the same issue. Removing the health check solved the issue for me

**Comment by webbson** [comment]
I experience the same issue. If the fix is as simple as removing the health check that should probably be done asap. :)

**Comment by RemCom** [comment]
I made a pull request for it to remove the health check

**Comment by frenck** [comment]
Fixed in #73
