### ISSUE TITLE
Error rendering multiple views: "hotconf not found"

### ISSUE THREAD

**Issue by jymbob** [hassio-addons/addon-emqx#62]
# Problem

I can't see several views inside EMQX, and am instead left on a loading screen. Inspecting the connection reports a failure to load "hotconf"

## Expected behavior

I expect to be able to see e.g. management MQTT settings

## Actual behavior

I see a loading page which never populates. There is a 404 in developer tools

## Steps to reproduce

- Install HAOS on an Ubuntu server (not sure this is required, but that's my system)
- Install EMQX
- open Web UI
- click Management -> MQTT settings

## Proposed changes

I've no idea what this file does, but it looks to me like the path hasn't been properly set, potentially due to an errant `/` at the start.

In Chrome devTools Network tab, for example, I can see a successful (200) fetch request for   
`https://<my-homeassistant-ip>/api/hassio_ingress/<plugin-id>/api/v5/stats`  
...followed by an unsuccessful (404) one to 
`https://<my-homeassistant-ip>/api/v5/schemas/hotconf`

note the lack of the `hassio_ingress` part of the path

I've had a quick look through the files in this repo, but couldn't see anything obvious, although I'm not familiar with how hassio plugins work. It may be that this needs something changing upstream?

**Comment by DN0000** [comment]
Having a similar issue:
![image](https://github.com/hassio-addons/addon-emqx/assets/5000002/36993697-f985-45a1-a724-315a2e43b787)

```
-----------------------------------------------------------
 Add-on: EMQX
 The most scalable open-source MQTT broker for IoT. An alternative for the Mosquitto add-on
-----------------------------------------------------------
 Add-on version: 0.2.10
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (amd64 / qemux86-64)
 Home Assistant Core: 2023.9.1
 Home Assistant Supervisor: 2023.08.3
-----------------------------------------------------------
```

Logs otherwise clean

**Comment by kloodhu** [comment]
same here. there is any solution? thx!

**Comment by seebaer1976** [comment]
Unfortunately the problem still exists in version 0.2.13
