### ISSUE TITLE
Topic metrics return 500 network error

### ISSUE THREAD

**Issue by andrejkolesa** [hassio-addons/addon-emqx#75]
I am using version  0.2.12

When i open Diagnose and Topic metric i get 500 network error

Also when i open Management and MQTT settings page does not load.

**Comment by mkubant** [comment]
I agree. I have the same problem.

**Comment by mkubant** [comment]
> I agree. I have the same problem.

api/v5/schemas/hotconf return 404

**Comment by mkubant** [comment]
What was already written in another issue worked for me.
---
As a workaround, it works when you open the admin page directly in a web browser instead of opening it through the HA interface.
