### ISSUE TITLE
Config doesnt appear to work 

### ISSUE THREAD

**Issue by johntdyer** [hassio-addons/addon-emqx#8]
# Problem/Motivation

Environment variables in config doesnt appear to work

## Expected behavior
`EMQ_NAME=foo` should work 
> (What you expected to happen)

## Actual behavior

![image](https://user-images.githubusercontent.com/58234/192542102-cb8adb93-2ae7-4481-a663-ff763b72b811.png)

## Steps to reproduce
I've tried 
EMQX_LISTENER__TCP__EXTERNAL="2883"
EMQX_NAME="foo"

## Proposed changes

I think an example config, or perhaps allow mapping a config from /config/emqx or something ? 

Thanks!

**Comment by frenck** [comment]
`EMQX_NAME=FOO`

is not valid YAML

`EMQX_NAME: "foo"`, however, is.
