### ISSUE TITLE
Add a bridge

### ISSUE THREAD

**Issue by HybridRCG** [hassio-addons/addon-emqx#9]
# Problem/Motivation 
I want to add a bridge to the EMQ X interface , Bridge dont seem to be subscribing.

> (Why the issue was filed)

## Expected behavior
subscribe to the bridge broker

> (What you expected to happen)

## Actual behavior
Dont see it subscribing

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes
In the standard mosquito broker you added a config file. Dont know where this config file might be created and into what format it requires it.

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
This is not a question about the add-on itself, but about EMQX. Add-ons wrap existing applications, in this case EMQX. Please consult the EMQX documentation and community for more information on how to use EMQX.

Thanks 👍 

../Frenck
