### ISSUE TITLE
Latest update to 0.6.0 cripples EMQX

### ISSUE THREAD

**Issue by hrikken** [hassio-addons/addon-emqx#98]
# Problem/Motivation

> When I apply the latest update, EQMX stops working. The dashboard isn't accessible anymore and the broker stops working

## Expected behavior

> I want to access the dashboard and MQTT should continue to work

## Actual behavior

> Dashboard can't be opened. MQTT broker stops working

## Steps to reproduce

> Just update to 0.6.0 (from 0.5.1)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by StrausFuenf** [comment]
Did you change some Env ars? 
You should also add your log output with update 0.5.0 there was also a change in EMQX where changes in EMQX_NODE__NAME was the problem.
With the log file we can try to find the problem.

**Comment by hrikken** [comment]
Thank you for your response! I've tried twice to update EQMX and I had to restore a backup to get it up and running again. I didn't change anything to ENV_VARS or anythoing else. So I carried out an update this morning to provide you with the log but strangely the update succeeded well! I'm running on 0.6.0 now and everything looks well. No data is lost. I'll let it run for now and let you know if anything happens. Thanks again.

**Comment by hrikken** [comment]
The dashboard became unresponsive again. The broker kept working. Had to restore the backup to access the dashboard.

**Comment by StrausFuenf** [comment]
That the version inside says 5.7.0 is ok. 0.6.0 is the Homeassistant Addon Version and 5.7.0 the EMQX version.
Dashboard getting unresponsive is weird.. Is it just inside the ingress window or also if you visit the Dashboard via Homeassistant-Ip:18083? Can you update and try that again?

**Comment by kriegerse** [comment]
At least I can confirm the observed behavior after updating to EMQX 0.6.0 no message got processed anymore and had to revert back to 0.5.1 from backup. "Unfortunately" updating today to 0.6.0 worked out well and I'm not able to reproduce the issue anymore to help with details here.

**Comment by hrikken** [comment]
That's exactly the same I experienced. Just wait for a day or so if EMQX keeps working properly.

**Comment by hrikken** [comment]
> That the version inside says 5.7.0 is ok. 0.6.0 is the Homeassistant Addon Version and 5.7.0 the EMQX version. Dashboard getting unresponsive is weird.. Is it just inside the ingress window or also if you visit the Dashboard via Homeassistant-Ip:18083? Can you update and try that again?

I suppose I visit the dashboard inside the ingress window.

**Comment by hrikken** [comment]
> That the version inside says 5.7.0 is ok. 0.6.0 is the Homeassistant Addon Version and 5.7.0 the EMQX version. Dashboard getting unresponsive is weird.. Is it just inside the ingress window or also if you visit the Dashboard via Homeassistant-Ip:18083? Can you update and try that again?

I've updated the addon to 0.6.0. Dashboard and broker are working. I'l let it run to see if it's stable. If the dashboard becomes unresponsive via the Ingress I'l try it via the IP/Port. Keep you posted..

**Comment by hrikken** [comment]
> > That the version inside says 5.7.0 is ok. 0.6.0 is the Homeassistant Addon Version and 5.7.0 the EMQX version. Dashboard getting unresponsive is weird.. Is it just inside the ingress window or also if you visit the Dashboard via Homeassistant-Ip:18083? Can you update and try that again?
> 
> I've updated the addon to 0.6.0. Dashboard and broker are working. I'l let it run to see if it's stable. If the dashboard becomes unresponsive via the Ingress I'l try it via the IP/Port. Keep you posted..

The dashboard via Ingress became unresponsive again. I tried the IP/Port method and that worked. So something is wrong with the ingress thing...
